---
engines:
  ruff:
    enabled: true
  pylint:
    enabled: true
    python_version: 3
    base_sub_dir: src/
  bandit:
    enabled: true
    base_sub_dir: src/
  markdownlint:
    enabled: true
  semgrep:
    enabled: false  # Disabled due to proprietary extension issues in CI

exclude_paths:
  - "tests/**"
  - "docs/**"
  - "htmlcov/**"
  - "*.egg-info/**"
  - "scripts/**"
