---
engines:
  ruff:
    enabled: true
  pylint:
    enabled: true
    python_version: 3
    base_sub_dir: src/
  bandit:
    enabled: true
    base_sub_dir: src/
  markdownlint:
    enabled: true
  semgrep:
    enabled: true

exclude_paths:
  # Test files - different patterns, not production code
  - "tests/**"

  # Documentation - separate from code
  - "docs/**"

  # Generated files and build artifacts
  - "htmlcov/**"
  - "*.egg-info/**"
  - "dist/**"
  - "build/**"
  - ".pytest_cache/**"
  - "**/__pycache__/**"

  # CI/CD configuration
  - ".github/**"

  # Shell scripts only (Python scripts in scripts/ will be analyzed)
  - "scripts/*.sh"

  # Legacy files if any
  - "**/*_old.py"
  - "**/*_backup.py"
