name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have tested with the latest version of claude-builder
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With project structure '...'
        3. See error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: Full error message and stack trace (if applicable)
      render: text
      placeholder: Paste the complete error output here...

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Python version (e.g., 3.11.2)
      placeholder: "3.11.2"
    validations:
      required: true

  - type: input
    id: claude-builder-version
    attributes:
      label: Claude Builder Version
      description: Version of claude-builder (run `claude-builder --version`)
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: project-type
    attributes:
      label: Project Type
      description: What type of project were you analyzing?
      options:
        - Python
        - Rust
        - JavaScript/TypeScript
        - Java
        - Go
        - Multiple languages
        - Other (specify in additional context)

  - type: textarea
    id: project-structure
    attributes:
      label: Project Structure
      description: Relevant parts of your project structure (if applicable)
      render: text
      placeholder: |
        project/
        ├── src/
        ├── tests/
        └── README.md

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your claude-builder configuration (if using custom config)
      render: json
      placeholder: |
        {
          "analysis": {
            "confidence_threshold": 80
          }
        }

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help
      placeholder: Add any other context about the problem here...
