name: 📋 Template Contribution
description: Submit a new template or template improvement
title: "[Template]: "
labels: ["template", "contribution", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a template! Templates help make Claude Builder more useful for specific project types.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      description: Please verify these items before submitting
      options:
        - label: I have tested this template with real projects
          required: true
        - label: The template follows Claude Builder naming conventions
          required: true
        - label: I have included proper variable substitution
          required: true
        - label: The template is original or properly attributed
          required: true

  - type: input
    id: template-name
    attributes:
      label: Template Name
      description: Name of the template (e.g., "python-microservice", "rust-cli-advanced")
      placeholder: "template-name"
    validations:
      required: true

  - type: dropdown
    id: template-type
    attributes:
      label: Template Type
      description: What type of template is this?
      options:
        - Language template (python, rust, javascript, etc.)
        - Framework template (django, fastapi, react, etc.)
        - Domain template (ecommerce, cli-tool, web-api, etc.)
        - Custom template (specific use case)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Template Description
      description: What does this template provide?
      placeholder: |
        Brief description of the template's purpose and what it generates...
        - Target project types
        - Key features included
        - Specific use cases
    validations:
      required: true

  - type: checkboxes
    id: languages
    attributes:
      label: Supported Languages
      description: Which languages does this template support?
      options:
        - label: Python
        - label: Rust
        - label: JavaScript/TypeScript
        - label: Java
        - label: Go
        - label: C++/C
        - label: Other (specify in description)

  - type: checkboxes
    id: frameworks
    attributes:
      label: Supported Frameworks
      description: Which frameworks does this template support?
      options:
        - label: FastAPI
        - label: Django
        - label: Flask
        - label: React
        - label: Vue.js
        - label: Express.js
        - label: Axum
        - label: Spring Boot
        - label: Other (specify in description)

  - type: checkboxes
    id: project-types
    attributes:
      label: Project Types
      description: Which project types does this template target?
      options:
        - label: Web API/Service
        - label: Web Frontend
        - label: CLI Tool
        - label: Library/Package
        - label: Data Science/ML
        - label: DevOps/Infrastructure
        - label: Game Development
        - label: Mobile App
        - label: Other (specify in description)

  - type: textarea
    id: files
    attributes:
      label: Template Files
      description: List the files included in this template
      render: text
      placeholder: |
        templates/your-template/
        ├── claude_instructions.md
        ├── agents_config.md
        ├── development_guide.md
        ├── project_structure.md
        └── custom_file.md
    validations:
      required: true

  - type: textarea
    id: variables
    attributes:
      label: Template Variables
      description: What variables does this template use?
      placeholder: |
        List the variables that get substituted in your template:
        - ${project_name} - Name of the project
        - ${language} - Primary programming language
        - ${framework} - Web/app framework
        - ${custom_var} - Description of custom variable
    validations:
      required: true

  - type: textarea
    id: example-output
    attributes:
      label: Example Output
      description: Show a snippet of what this template generates
      render: markdown
      placeholder: |
        ```markdown
        # Example CLAUDE.md section generated by this template
        
        ## Project: ${project_name}
        
        This is a ${language} ${framework} project that...
        ```

  - type: textarea
    id: test-projects
    attributes:
      label: Tested Projects
      description: What projects have you tested this template with?
      placeholder: |
        List example projects or project characteristics you've tested:
        - Project type 1: specific example or description
        - Project type 2: specific example or description
    validations:
      required: true

  - type: dropdown
    id: quality
    attributes:
      label: Template Quality
      description: How thoroughly have you tested this template?
      options:
        - Basic (works for simple cases)
        - Good (tested with multiple projects)
        - Excellent (thoroughly tested, handles edge cases)
        - Production (used in real projects successfully)
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: How should this template be integrated?
      placeholder: |
        - Where should the template files be placed?
        - Are there any special integration requirements?
        - Should this extend an existing template?
        - Any configuration needed?

  - type: checkboxes
    id: contribution-type
    attributes:
      label: Contribution Type
      description: How are you contributing this template?
      options:
        - label: New template files attached/linked
        - label: Pull request with template files
        - label: Template code in this issue
        - label: Link to external template repository

  - type: textarea
    id: template-content
    attributes:
      label: Template Content
      description: Paste template content or provide links
      placeholder: |
        Either paste the template files here or provide links to:
        - GitHub repository
        - File attachments
        - Pull request
        
        If pasting content, please use code blocks with appropriate syntax highlighting.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about this template
      placeholder: |
        - Inspiration or source for this template
        - Special features or capabilities
        - Future enhancement ideas
        - Community need this addresses